- name: Configuración y puesta a punto del servidor
  hosts: all
  become: yes

  vars:
    mysql_root_password: "root"
    docker_container_name: "tuxoutAPP"

  tasks:

    - name: Incluir tareas de dependencies
      import_tasks: dependencies.yml

    - name: Incluir tareas de mysql
      import_tasks: mysql.yml

    - name: Incluir tareas de firewall
      import_tasks: firewall.yml
